version: "3"
services: 
  portainer:
    image: portainer/portainer-ce:2.9.3
    container_name: portainer
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer_data:/data
    ports: 
      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    networks:
      - pro
networks:
  pro:
    driver: bridge
